Repository Team-AVT/AirViewer2, pull requests merged in 2022-04, with the labels that each got.

#16 Added some new dependencies and plugins to pom.xml file.
  pom.xml
Labels: documentation, enhancement

#18 Edited Product Backlog for Sprint1
  ProductBacklog.txt
Labels: documentation

#19 Added AddPages.java file as per the contract.
  src/main/java/edu/wright/airviewer2/AddPages.java
Labels: enhancement

#17 Updated ContractForProgramming_Dorayya62.txt with a new contract
  Contracts for Programming/ContractForProgramming_Dorayya62.txt
Labels: documentation

#20 Added contract for DeletePages class.
  Contracts for Programming/ContractForProgramming_Dorayya62.txt
Labels: documentation

#21 Coded DeletePages class as per the contract.
  src/main/java/edu/wright/airviewer2/DeletePages.java
Labels: enhancement

#22 Added test case to test Add Pages functionality
  src/test/java/edu/wright/airviewer2/TestAddPages.java
Labels: Testing

#23 Added code coverage file for TestAddPages.java
  Code Coverage under the tests/TestAddPagesCoverage.html
Labels: Testing

#24 Debugged the code in the class DeletePages.
  src/main/java/edu/wright/airviewer2/DeletePages.java
Labels: bug

#25 Added test case to test Delete Page functionality
  src/test/java/edu/wright/airviewer2/TestDeletePages.java
Labels: Testing

#26 Added Code Coverage file for TestDeletePages.java
  Code Coverage under the tests/TestDeletePagesCoverage.html
Labels: Testing

#27 Added "Add Blank Pages" button under "Edit" menu in the UI.
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/java/edu/wright/airviewer2/AIRViewerModel.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: enhancement

#28 Deleted .html file and added zip file for code coverage of Add Pages functionality due to some compatibility issues
  Code Coverage under the tests/TestAddPagesCoverage.zip
Labels: documentation

#29 Deleted .html file and replaced with .zip file with all files for Code Coverage of DeletePages functionality due to some compatibility issues.
  Code Coverage under the tests/TestDeletePagesCoverage.html
  Code Coverage under the tests/TestDeletePagesCoverage.zip
Labels: documentation

#30 Added the button "Delete a Page", on clicking which opens a Dialogue Box that takes the page number from the user to delete that page.
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: enhancement

#31 Added a contract to program ToDoc class
  Contracts for Programming/ContractForProgramming_pajayreddy.txt
Labels: documentation

#32 Added ToDoc class as per the contract
  src/main/java/edu/wright/airviewer2/ToDoc.java
Labels: enhancement

#33 Added contract to code ToPPT class.
  Contracts for Programming/ContractForProgramming_pajayreddy.txt
Labels: documentation

#34 Coded and added ToPPT class as per the contract
  src/main/java/edu/wright/airviewer2/ToPPT.java
Labels: enhancement

#35 Added contract to code ToHTML class
  Contracts for Programming/ContractForProgramming_pajayreddy.txt
Labels: documentation

#36 Coded and added ToHTML class as per the contract
  src/main/java/edu/wright/airviewer2/ToHTML.java
Labels: enhancement

#38 Added Test Case to test Convert to PPT function.
  src/test/java/edu/wright/airviewer2/TestToPPT.java
Labels: Testing

#40 Added Code Coverage under TestToDoc test case.
  Code Coverage under the tests/TestToDocCoverage.zip
Labels: Testing

#41 Added Code Coverage under TestToPPT test case.
  Code Coverage under the tests/TestToPPTCoverage.zip
Labels: Testing

#42 Added Code Coverage under TestToHTML test case
  Code Coverage under the tests/TestToHTMLCoverage.zip
Labels: Testing

#43 Created a new menu "Convert" and added all the conversion buttons under that.
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: enhancement

#44 Added Sprint1 retrospective
  sprint 1 retrospective.txt
Labels: documentation

#45 Added SDD at the end of Sprint1.
  Sprint 1 Design Document.zip
Labels: documentation

#61 Added contract to code HighlightText class (Issue #51).
  Contracts for Programming/ContractForProgramming_Dorayya62.txt
Labels: documentation

#62 Added HighlightText.java class as per the contract (Issue #51)
  src/main/java/edu/wright/airviewer2/HighlightText.java
Labels: enhancement

#63 Added contract to code ReplaceText class (Issue #57).
  Contracts for Programming/ContractForProgramming_Dorayya62.txt
Labels: documentation

#64 Coded and added ReplaceText class as per contract (Issue #57)
  src/main/java/edu/wright/airviewer2/ReplaceText.java
Labels: enhancement

#65 Added contract to code SetFontSize class (Issue #54)
  Contracts for Programming/ContractForProgramming_Dorayya62.txt
Labels: documentation

#66 Coded and added SetFontSize class as per contract (Issue #54)
  src/main/java/edu/wright/airviewer2/SetFontSize.java
Labels: enhancement

#67 Added a J Unit test case to test HighlightText functionality and provided code coverage under that Test case (Issue #52)
  Code Coverage under the tests/TestHighlightTextCoverage.zip
  src/test/java/edu/wright/airviewer2/TestHighlightText.java
Labels: Testing

#68 Added a J Unit test case to test ReplaceText functionality and provided code coverage under that Test case (Issue #58)
  Code Coverage under the tests/TestReplaceTextCoverage.zip
  src/test/java/edu/wright/airviewer2/TestReplaceText.java
Labels: Testing

#69 Added a J Unit test case to test SetFontSize functionality and provided code coverage under that Test case (Issue #55)
  Code Coverage under the tests/TestSetFontSizeCoverage.zip
  src/test/java/edu/wright/airviewer2/TestSetFontSize.java
Labels: Testing

#70 Added Highlight Text button in UI under Edit menu which gives user an option to Highlight a text in a PDF (Issue #53)
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: enhancement

#71 Added "Replace Text" button in UI under Edit menu which gives user an option to Highlight a text in a PDF (Issue #53)
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: enhancement

#72 Added "Set Font Size Text" button in UI under Edit menu which gives user an option to set font size of a text in a PDF (Issue #56)
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: enhancement

#73 Added contract to code SetPassword class with a method that can set password to a PDF (Issue #47)
  Contracts for Programming/ContractForProgramming_pajayreddy.txt
Labels: documentation

#74 Added SetPassword class as per contract (Issue #47)
  src/main/java/edu/wright/airviewer2/SetPassword.java
Labels: enhancement

#76 Added "Set Password" button in UI with Dialogue box (Issue #49)
  src/main/java/edu/wright/airviewer2/AIRViewerController.java
  src/main/resources/edu/wright/airviewer2/AIRFXMLDocument.fxml
Labels: enhancement
